/**
 * Structured data (JSON-LD) for the site.
 *
 * Only blog posts carried any before this, and the one they carried was
 * self-contained: a bare `author: {name}` with no identity behind it, and a
 * publisher logo pointing at /images/logo.png, which does not exist.
 *
 * Everything here hangs off one Person node with a stable @id. Every other
 * node — articles, projects, talks, the site itself — references that @id
 * rather than restating the name, so a crawler sees one entity mentioned in
 * many places instead of a dozen unrelated people who happen to share a name.
 * That single-entity shape is what feeds a knowledge panel; scattered
 * Person objects do not.
 *
 * Content comes from src/data/personalInfo.js and src/lib/navigation.js so the
 * markup can't drift from what the pages themselves render.
 */

import { SITE_URL } from './siteUrl';
import { SOCIAL_LINKS } from './navigation';
import { personalInfo } from '../data/personalInfo';

export const PERSON_ID = `${SITE_URL}/#person`;
export const WEBSITE_ID = `${SITE_URL}/#website`;

/** Schema.org wants absolute URLs; frontmatter stores site-relative ones. */
export function absoluteUrl(pathOrUrl) {
  if (!pathOrUrl) return undefined;
  if (/^https?:\/\//.test(pathOrUrl)) return pathOrUrl;
  return `${SITE_URL}${pathOrUrl.startsWith('/') ? '' : '/'}${pathOrUrl}`;
}

/** The default social card, generated by app/opengraph-image.js. */
const DEFAULT_IMAGE = `${SITE_URL}/opengraph-image`;

/**
 * The one Person node. Everything else points at PERSON_ID instead of
 * duplicating this.
 */
export function personNode() {
  return {
    '@type': 'Person',
    '@id': PERSON_ID,
    name: personalInfo.name,
    url: `${SITE_URL}/`,
    image: {
      '@type': 'ImageObject',
      url: `${SITE_URL}/images/headshot.jpg`,
      caption: personalInfo.name,
    },
    description: personalInfo.bio,
    jobTitle: personalInfo.currentRole,
    worksFor: {
      '@type': 'Organization',
      name: personalInfo.company,
      url: 'https://cursor.com',
    },
    knowsAbout: personalInfo.expertise,
    sameAs: [
      SOCIAL_LINKS.github,
      SOCIAL_LINKS.linkedin,
      SOCIAL_LINKS.instagram,
      SOCIAL_LINKS.twitter,
    ].filter(Boolean),
  };
}

/** The site itself, attributed to the Person rather than a stand-in company. */
export function websiteNode() {
  return {
    '@type': 'WebSite',
    '@id': WEBSITE_ID,
    url: `${SITE_URL}/`,
    name: personalInfo.name,
    description: personalInfo.bio,
    inLanguage: 'en-US',
    publisher: { '@id': PERSON_ID },
  };
}

/**
 * @param {{name: string, path: string}[]} trail Home is prepended for you.
 */
export function breadcrumbNode(trail) {
  const items = [{ name: 'Home', path: '/' }, ...trail];
  return {
    '@type': 'BreadcrumbList',
    '@id': `${absoluteUrl(items[items.length - 1].path)}#breadcrumb`,
    itemListElement: items.map((crumb, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: crumb.name,
      item: absoluteUrl(crumb.path),
    })),
  };
}

/**
 * An ordered list of things that live at their own URLs — the blog index, the
 * project index, the talk list. `url` alone is deliberate: repeating each item's
 * full description here would duplicate what the item's own page already says.
 */
export function itemListNode({ id, name, description, urls }) {
  return {
    '@type': 'ItemList',
    '@id': id,
    name,
    description,
    numberOfItems: urls.length,
    itemListElement: urls.map((url, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      url: absoluteUrl(url),
    })),
  };
}

/** A blog post or project write-up. */
export function articleNode({
  title,
  description,
  image,
  date,
  updated,
  path,
  tags,
}) {
  const url = absoluteUrl(path);
  return {
    '@type': 'BlogPosting',
    '@id': `${url}#article`,
    headline: title,
    description,
    url,
    mainEntityOfPage: { '@type': 'WebPage', '@id': url },
    image: absoluteUrl(image) || DEFAULT_IMAGE,
    datePublished: date,
    // Google treats a missing dateModified as "never updated", so fall back to
    // the publish date rather than omitting it.
    dateModified: updated || date,
    // Author and publisher are the same person; there is no organisation here.
    author: { '@id': PERSON_ID },
    publisher: { '@id': PERSON_ID },
    inLanguage: 'en-US',
    keywords: tags && tags.length ? tags.join(', ') : undefined,
    isPartOf: { '@id': WEBSITE_ID },
  };
}

/**
 * A talk or workshop.
 *
 * Talks have no page of their own — they are all described on /speaking — so
 * `anchor` distinguishes the nodes by fragment and `url` points at the page
 * that actually exists. Minting /speaking/<slug> @ids here would advertise URLs
 * that 404.
 */
export function eventNode({
  title,
  description,
  date,
  venue,
  location,
  anchor,
  registrationUrl,
  isUpcoming,
}) {
  const page = `${SITE_URL}/speaking`;
  return {
    '@type': 'Event',
    '@id': `${page}#${anchor}`,
    name: title,
    // Several talks carry a description identical to the event name; emitting
    // both just repeats the string.
    description: description && description !== title ? description : undefined,
    startDate: date,
    url: page,
    eventStatus: 'https://schema.org/EventScheduled',
    eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode',
    // performer only. He speaks at these; he does not run them — MongoDB.local
    // and the Developer Days are organised by MongoDB. Claiming organizer would
    // be a false statement about a real event.
    performer: { '@id': PERSON_ID },
    location:
      venue || location
        ? {
            '@type': 'Place',
            name: venue || location,
            address: location || undefined,
          }
        : undefined,
    // Only meaningful while the event is still ahead; a registration link on a
    // past talk reads as an active offer.
    offers:
      isUpcoming && registrationUrl
        ? {
            '@type': 'Offer',
            url: registrationUrl,
            availability: 'https://schema.org/InStock',
          }
        : undefined,
  };
}

/**
 * Wrap nodes in a single @graph. One script tag per page, so the nodes can
 * reference each other by @id.
 *
 * Person and WebSite are included on every page, not just the homepage. A
 * reference like `author: { '@id': '…#person' }` is only resolvable if the node
 * it names is in the same document — otherwise Google reads the article as
 * having an author with no name and drops it from rich results. Repeating the
 * two identity nodes per page costs about a kilobyte and is what every
 * well-formed site does.
 */
export function graph(...nodes) {
  return {
    '@context': 'https://schema.org',
    '@graph': [personNode(), websiteNode(), ...nodes.flat()].filter(Boolean),
  };
}
