import { coverImageSize } from '../../../lib/imageSize';
import JsonLd from '../../../components/JsonLd';
import { absoluteUrl, articleNode, breadcrumbNode, graph } from '../../../lib/structuredData';
import { getPostBySlug, getAllPosts } from '../../../lib/blog';
import { BlogLayout } from '../../../components/blog/BlogLayout';
import BlogPostContent from '../../../components/blog/BlogPostContent';
import { notFound } from 'next/navigation';
import { SITE_URL } from '../../../lib/siteUrl';

export async function generateStaticParams() {
  const projects = await getAllPosts('project');
  return projects.map((project) => ({
    slug: project.slug,
  }));
}

/**
 * The one image that represents a project, used for og:image, twitter:image and
 * the JSON-LD `image` alike — they must agree, or the page tells scrapers one
 * thing and Google another.
 *
 * A cover is used as-is when it is at least 1200x627, LinkedIn's threshold for
 * the large image card and comfortably past Google's 1200px-wide Article
 * guidance. Below that — nine project covers are app screenshots around 950x720
 * — the page uses the card generated by ./opengraph-image.js instead. Upscaling
 * a screenshot looks soft; drawing a real card from the project's own title and
 * stack does not. The generated card is a fallback, never a replacement for
 * artwork that is already big enough.
 *
 * absoluteUrl, not string concatenation: some covers are stored as full URLs on
 * Vercel Blob, and prefixing SITE_URL to those produced a dead image.
 */
function projectCardImage(project, slug) {
  const coverSize = coverImageSize(project.image);
  const coverIsLargeEnough =
    coverSize && coverSize.width >= 1200 && coverSize.height >= 627;

  if (project.image && coverIsLargeEnough) {
    return { url: absoluteUrl(project.image), ...coverSize, alt: project.title };
  }
  return {
    url: `${SITE_URL}/projects/${slug}/opengraph-image`,
    width: 1200,
    height: 630,
    alt: project.title,
  };
}

export async function generateMetadata({ params }) {
  const project = await getPostBySlug(params.slug);
  if (!project) return {};

  const fullUrl = `${SITE_URL}/projects/${params.slug}`;
  const card = projectCardImage(project, params.slug);

  return {
    title: project.title,
    description: project.description,
    authors: [{ name: project.author }],
    alternates: {
      canonical: `${SITE_URL}/projects/${params.slug}`,
    },
    openGraph: {
      title: project.title,
      description: project.description,
      type: 'article',
      url: fullUrl,
      siteName: 'Michael Lynn',
      publishedTime: project.date,
      modifiedTime: project.updated || project.date,
      authors: [project.author],
      images: [card],
    },
    twitter: {
      card: 'summary_large_image',
      title: project.title,
      description: project.description,
      images: [card.url],
      creator: '@mlynn',
    },
  };
}

export default async function Project({ params }) {
  const project = await getPostBySlug(params.slug);
  
  // Unknown slugs used to render this message with a 200, so retired and
  // mistyped URLs looked like real, thin pages to crawlers. notFound()
  // sends a real 404 and renders app/not-found.js.
  if (!project) {
    notFound();
  }

  // Emitted here rather than inside BlogLayout, which is a client
  // component — structured data has to be in the server-rendered HTML.
  // Same resolution as generateMetadata, so the JSON-LD image and og:image never
  // disagree about which picture represents this project.
  const card = projectCardImage(project, params.slug);

  const articleGraph = graph(
    articleNode({
      title: project.title,
      description: project.description,
      image: card.url,
      date: project.date,
      updated: project.updated,
      path: `/projects/${params.slug}`,
      tags: project.tags,
    }),
    breadcrumbNode([
      { name: 'Projects', path: '/projects' },
      { name: project.title, path: `/projects/${params.slug}` },
    ])
  );

  return (
    <>
      <JsonLd data={articleGraph} />
      <BlogLayout
        title={project.title}
        description={project.description}
        image={project.image}
        date={project.date}
        author={project.author}
        demoUrl={project.demoUrl}
        githubUrl={project.githubUrl}
      >
        <BlogPostContent post={project} slug={params.slug} />
      </BlogLayout>
    </>
  );
}
