import { coverImageSize } from '../../../lib/imageSize';
import JsonLd from '../../../components/JsonLd';
import { absoluteUrl, articleNode, breadcrumbNode, graph } from '../../../lib/structuredData';
import { getPostBySlug, getAllPosts } from '../../../lib/blog';
import { BlogLayout } from '../../../components/blog/BlogLayout';
import BlogPostContent from '../../../components/blog/BlogPostContent';
import { notFound } from 'next/navigation';
import { SITE_URL } from '../../../lib/siteUrl';

export async function generateStaticParams() {
  const posts = await getAllPosts();
  return posts.map((post) => ({
    slug: post.slug,
  }));
}

/**
 * The one image that represents a post, used for og:image, twitter:image and the
 * JSON-LD `image` alike — they must agree, or the page tells scrapers one thing
 * and Google another.
 *
 * A cover is used as-is when it is at least 1200x627: LinkedIn's threshold for
 * the large image card, and past Google's 1200px-wide Article guidance. Below
 * that the page uses the card generated by ./opengraph-image.js instead. Four
 * posts carry 640px stock photos, and upscaling those looks worse than drawing a
 * real card.
 *
 * Project posts render here too but canonicalise to /projects/<slug>, so they
 * take the project card — otherwise the two URLs for the same write-up would
 * advertise different images.
 *
 * An unmeasurable cover counts as too small. Three covers live on Vercel Blob as
 * full URLs, and measuring those would mean fetching them during the build. All
 * three happen to be 640px, so the generated card is the right answer today; a
 * remote cover worth keeping should move into public/ where it can be measured.
 *
 * absoluteUrl, not string concatenation: prefixing SITE_URL to one of those full
 * URLs produced a dead image.
 */
function postCardImage(post, slug) {
  const segment = post.category === 'project' ? 'projects' : 'blog';
  const coverSize = coverImageSize(post.image);
  const coverIsLargeEnough =
    coverSize && coverSize.width >= 1200 && coverSize.height >= 627;

  if (post.image && coverIsLargeEnough) {
    return { url: absoluteUrl(post.image), ...coverSize, alt: post.title };
  }
  return {
    url: `${SITE_URL}/${segment}/${slug}/opengraph-image`,
    width: 1200,
    height: 630,
    alt: post.title,
  };
}

export async function generateMetadata({ params }) {
  const post = await getPostBySlug(params.slug);
  if (!post) return {};

  // Project posts also render at /projects/<slug>, which is where they are
  // linked from and listed. Point the canonical there so the two URLs don't
  // compete as duplicate content.
  const canonicalPath =
    post.category === 'project' ? `/projects/${params.slug}` : `/blog/${params.slug}`;
  const fullUrl = `${SITE_URL}${canonicalPath}`;
  const card = postCardImage(post, params.slug);

  return {
    title: post.title,
    description: post.description,
    authors: [{ name: post.author }],
    alternates: {
      canonical: fullUrl,
    },
    openGraph: {
      title: post.title,
      description: post.description,
      type: 'article',
      url: fullUrl,
      siteName: 'Michael Lynn',
      publishedTime: post.date,
      modifiedTime: post.updated || post.date,
      authors: [post.author],
      images: [card],
    },
    twitter: {
      card: 'summary_large_image',
      title: post.title,
      description: post.description,
      images: [card.url],
      creator: '@mlynn',
    },
  };
}

export default async function BlogPost({ params }) {
  const post = await getPostBySlug(params.slug);
  
  // Unknown slugs used to render this message with a 200, so retired and
  // mistyped URLs looked like real, thin pages to crawlers. notFound()
  // sends a real 404 and renders app/not-found.js.
  if (!post) {
    notFound();
  }

  // Emitted here rather than inside BlogLayout, which is a client
  // component — structured data has to be in the server-rendered HTML.
  // Project posts render here too but canonicalise to /projects/<slug>, the
  // same split generateMetadata above makes. The structured data has to follow
  // the canonical, or @id and mainEntityOfPage name a URL that the page itself
  // says is not the real one.
  const isProject = post.category === 'project';
  const articlePath = isProject
    ? `/projects/${params.slug}`
    : `/blog/${params.slug}`;

  // Same resolution as generateMetadata, so the JSON-LD image and og:image never
  // disagree about which picture represents this post.
  const card = postCardImage(post, params.slug);

  const articleGraph = graph(
    articleNode({
      title: post.title,
      description: post.description,
      image: card.url,
      date: post.date,
      updated: post.updated,
      path: articlePath,
      tags: post.tags,
    }),
    breadcrumbNode([
      isProject
        ? { name: 'Projects', path: '/projects' }
        : { name: 'Writing', path: '/blog' },
      { name: post.title, path: articlePath },
    ])
  );

  return (
    <>
      <JsonLd data={articleGraph} />
      <BlogLayout
        title={post.title}
        description={post.description}
        image={post.image}
        date={post.date}
        author={post.author}
        demoUrl={post.demoUrl}
        githubUrl={post.githubUrl}
        slug={params.slug}
        enableAskArticle
      >
        <BlogPostContent post={post} slug={params.slug} />
      </BlogLayout>
    </>
  );
}
